FROM ubuntu:focal
LABEL maintainer="mat3x@mail.ru"
RUN apt-get update
RUN apt-get install -y g++ nano
WORKDIR /root/test/
COPY homework_mp_5.1.1.cpp . 
# RUN g++ hello_world.cpp -o hello_world
#  CMD ["./hello_world"]
	